### ISSUE TITLE
Suggested README improvement: add note how to use key formatter without conversion

### ISSUE THREAD

**Issue by grubersjoe** [EventSaucePHP/ObjectHydrator#34]
Hey. Great package, thanks for sharing this 😊! 

I had the issue that the API I am consuming returns JSON payloads with camelCase property key names, so mapping `firstName` in the response array to `$firstName` in the value object did not work for me. However, after looking into the code I realized that I can use the `KeyFormatterWithoutConversion` class as `keyFormatter` argument in the constructor to disable key name conversion. So this solves my problem 👌.

```php
$mapper = new ObjectMapperUsingReflection(
    new DefinitionProvider(
        keyFormatter: new KeyFormatterWithoutConversion(),
    ),
);
```

I would suggest adding a small note about this in the README. I can imagine that more people might run into this little issue.

If you like I can also open a PR.

**Comment by frankdejonge** [comment]
Hi :) A PR would be very welcome, I'll check out if I can add a docs website for this project soon.

**Comment by grubersjoe** [comment]
Nice. I've created a MR.

**Comment by frankdejonge** [comment]
Thank you!
