### ISSUE TITLE
Object mapping seems to fail in versions 1.1.1 and above

### ISSUE THREAD

**Issue by TristanWeij** [EventSaucePHP/ObjectHydrator#38]
Hi,

I just updated my dependencies, and noticed that my testsuite started to fail after bumping to version `1.1.2`:
```shell
- Upgrading eventsauce/object-hydrator (1.0.0 => 1.1.2)
```

After some research, it seems that the following [commit](https://github.com/EventSaucePHP/ObjectHydrator/commit/be8673eaa4510fd859f8b0b65c1fb10462b0c603) causes an anomaly in `src/NaivePropertyTypeResolver.php`.

Seems like reintroducing `$commentTypeMap[$paramName] = $type;` fixes the issue. 🤔

```php
if (str_starts_with($type, '\\') || in_array($type, ['bool', 'boolean', 'int', 'integer', 'float', 'double', 'string', 'array', 'object', 'null'])) {
	$commentTypeMap[$paramName] = $type;
	continue;
}
```

**Comment by frankdejonge** [comment]
Hi @TristanWeij, can you supply a case where it fails? Otherwise it's difficult to ensure it won't regress again.
