### ISSUE TITLE
Missing implementation of abstract method...

### ISSUE THREAD

**Issue by plugowski** [EventSaucePHP/ObjectHydrator#42]
Hi, you forgot to implement method (public function serializeObjectOfType(object $object, string $className): mixed; ) from interface in OptimizedMapper :( 

```
PHP Fatal error:  Class ***\Infrastructure\Serialization\Mapper\OptimizedMapper contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (EventSauce\ObjectHydrator\ObjectMapper::serializeObjectOfType) in /var/www/html/vendor/***/src/Infrastructure/Serialization/Mapper/OptimizedMapper.php on line 16
```

**Comment by frankdejonge** [comment]
Hi, I think you need to re-generate your mapper. The generated mapper should contain it: https://github.com/EventSaucePHP/ObjectHydrator/blob/main/src/ObjectMapperCodeGenerator.php#L125 The tests also always validate that the method is there.
