### ISSUE TITLE
Regression when casting `null` into nullable enum

### ISSUE THREAD

**Issue by devfrey** [EventSaucePHP/ObjectHydrator#51]
Version `1.2.0` [removed a null check after looping over property casts](https://github.com/EventSaucePHP/ObjectHydrator/compare/1.1.3...1.2.0#diff-91947c6d413995d7e1da7473d7c71bbc51611de1b5dbaded60cae92d37a65c1dL107-L110). I have a weird edge case where I cast an empty string to `null` before letting ObjectHydrator set my `?CustomEnum`-typed property.

Consider this property caster:
```php
#[Attribute(Attribute::TARGET_PROPERTY)]
class CastEmptyStringToNull implements PropertyCaster
{
    public function cast(mixed $value, ObjectMapper $hydrator): mixed
    {
        if ($value === '') {
            return null;
        }

        return $value;
    }
}
```

and this object:
```php
class MyObject
{
    public function __construct(
        #[CastEmptyStringToNull]
        public readonly ?CustomEnum $enum,
    ) {
    }
}
```

This used to work, but since `1.2.0` throws a TypeError:
```
CustomEnum::from(): Argument #1 ($value) must be of type string, null given
```

I considered PR'ing the following fix, but I'm unsure how to apply the same fix to the code generator:

```diff
 # ObjectMapperUsingReflection.php

 foreach ($definition->casters as [$caster, $options]) {
     // ...
 
+    if ($value === null) {
+        goto set_value;
+    }
 }
```

Failing tests can be found in https://github.com/EventSaucePHP/ObjectHydrator/pull/52.

**Comment by frankdejonge** [comment]
Fixed in 1.4.0
