### ISSUE TITLE
No proper way to use anything but file for ObjectMapperCodeGenerator

### ISSUE THREAD

**Issue by vlakarados** [EventSaucePHP/ObjectHydrator#55]
Seems there's no way to use anything but dumping to file (memcache, apcu, etc.).
Would be great if you could turn definitions to json or `serialize()` and save somewhere else.

For now as a workaround I use 

        $d = new ObjectMapperCodeGenerator();
        $c = $d->dump([Client::class], 'My\File');
        eval('?>'.str_replace('declare(strict_types=1);', '', $c));

The `str_replace()` is there because of an error when trying to eval: `Fatal error: strict_types declaration must be the very first statement in the script in /var/www/core/src/Command/BuildCommand.php(30) : eval()'d code on line 3`.

Also it's not possible to use a class without a namespace.

I guess much of this was based on a decision to speed things up, but does dumping a bunch of hardcode really makes that much of a difference instead of iterating over a cached array?

**Comment by vlakarados** [comment]
Maybe generating some code for `eval()` and provisioning to an existing class would be better in such case? This would help much with static analysis as well.

Generated methods as `serializeObjectX()` can be provisioned to the builder class and passed as anonymous functions. Currently too much of the code is generated which is static by it's nature. This would produce a much more user-extendable solution.

**Comment by vlakarados** [comment]
Use case - I want to cache this in APCu or Memcache/Redis/etc, not a file (which is a hassle to update dynamically and commit to git every time)

**Comment by frankdejonge** [comment]
You can make a proxy class quite easily which use a cache and the code generator to fetch the cache entry (and fall back to the code generator), after which you use `eval` to load the logic. Nothing in the design obstructs you from doing this.

**Comment by frankdejonge** [comment]
Ok, so... problem solved then?

**Comment by vlakarados** [comment]
I did find a workaround for my problem. The answer to your question is your call, you know what's best for the project.
