### ISSUE TITLE
Which license options?

### ISSUE THREAD

**Issue by Eddy84** [EventSaucePHP/ObjectHydrator#59]
Hi,
your library seems to provide exactly what I have been looking for in the PHP universe. 

Great work!

Do you plan to release the library under the MIT license?

Many commercial projects need to make sure the license requirements are fulfilled in order to use third party code.

Best regards

**Comment by froschdesign** [comment]
@Eddy84 
In the Composer configuration you can find the "MIT" licence:

https://github.com/EventSaucePHP/ObjectHydrator/blob/366af189cd45d8474f08e3d55e0c932508c5a80a/composer.json#L5

But this repository needs [some more configuration](https://github.com/EventSaucePHP/ObjectHydrator/community) that the licence is also listed here on GitHub.

**Comment by frankdejonge** [comment]
I've added the MIT license file.
