### ISSUE TITLE
Feature: hydrate multiple objects into "typed array"

### ISSUE THREAD

**Issue by JanMikes** [EventSaucePHP/ObjectHydrator#9]
So far I have been using https://packagist.org/packages/symplify/easy-hydrator which has unfortunately been deprecated. API and functionality seems to be very close to each other.

Though i miss one important feature and that is hydrating multiple objects at once:
```php
/** @var array<MyClass> $data */
$hydrator->hydrateObjects(MyClass::class, $data);
```

Right now i am using:
```php
$objects = [];
foreach ($data as $objectData) {
    $objects[] = $hydrator->hydrateObject(MyClass::class, $objectData);
}
```

Are you opened to support such functionality? I am able to send PR if you confirm. Thank you

**Comment by frankdejonge** [comment]
Hi, Jan. Please check out https://github.com/EventSaucePHP/ObjectHydrator/pull/11

**Comment by JanMikes** [comment]
Hi, looks good!
